// Mocks generated by Mockito 5.4.6 from annotations
// in v5_app/test/providers/task_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:v5_app/modules/points/models/points_model.dart' as _i3;
import 'package:v5_app/modules/tasks/models/task_model.dart' as _i2;
import 'package:v5_app/modules/tasks/repositories/task_repository.dart' as _i4;
import 'package:v5_app/providers/points_provider.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTask_0 extends _i1.SmartFake implements _i2.Task {
  _FakeTask_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserPoints_1 extends _i1.SmartFake implements _i3.UserPoints {
  _FakeUserPoints_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRepository extends _i1.Mock implements _i4.TaskRepository {
  MockTaskRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.Task>> getTasksForDate(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#getTasksForDate, [date]),
            returnValue: _i5.Future<List<_i2.Task>>.value(<_i2.Task>[]),
          )
          as _i5.Future<List<_i2.Task>>);

  @override
  _i5.Future<_i2.Task> addTask(_i2.Task? task) =>
      (super.noSuchMethod(
            Invocation.method(#addTask, [task]),
            returnValue: _i5.Future<_i2.Task>.value(
              _FakeTask_0(this, Invocation.method(#addTask, [task])),
            ),
          )
          as _i5.Future<_i2.Task>);

  @override
  _i5.Future<void> generateRecurringTasks(_i2.Task? task) =>
      (super.noSuchMethod(
            Invocation.method(#generateRecurringTasks, [task]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateTask(_i2.Task? task, {bool? updateAll = false}) =>
      (super.noSuchMethod(
            Invocation.method(#updateTask, [task], {#updateAll: updateAll}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteTask(int? id, {bool? deleteAll = false}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTask, [id], {#deleteAll: deleteAll}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> completeTask(_i2.Task? task) =>
      (super.noSuchMethod(
            Invocation.method(#completeTask, [task]),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> uncompleteTask(_i2.Task? task) =>
      (super.noSuchMethod(
            Invocation.method(#uncompleteTask, [task]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.Task>> getAllTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTasks, []),
            returnValue: _i5.Future<List<_i2.Task>>.value(<_i2.Task>[]),
          )
          as _i5.Future<List<_i2.Task>>);

  @override
  _i5.Future<List<_i2.Task>> getRecurringTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getRecurringTasks, []),
            returnValue: _i5.Future<List<_i2.Task>>.value(<_i2.Task>[]),
          )
          as _i5.Future<List<_i2.Task>>);

  @override
  _i5.Future<void> autoCheckRecurringTasks() =>
      (super.noSuchMethod(
            Invocation.method(#autoCheckRecurringTasks, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> checkOverdueTasks() =>
      (super.noSuchMethod(
            Invocation.method(#checkOverdueTasks, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.Task> restoreTaskFromRecycle(int? recycledTaskId) =>
      (super.noSuchMethod(
            Invocation.method(#restoreTaskFromRecycle, [recycledTaskId]),
            returnValue: _i5.Future<_i2.Task>.value(
              _FakeTask_0(
                this,
                Invocation.method(#restoreTaskFromRecycle, [recycledTaskId]),
              ),
            ),
          )
          as _i5.Future<_i2.Task>);

  @override
  _i5.Future<void> deleteFromRecycle(int? recycledTaskId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFromRecycle, [recycledTaskId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearRecycleBin() =>
      (super.noSuchMethod(
            Invocation.method(#clearRecycleBin, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.RecycledTask>> getRecycledTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getRecycledTasks, []),
            returnValue: _i5.Future<List<_i2.RecycledTask>>.value(
              <_i2.RecycledTask>[],
            ),
          )
          as _i5.Future<List<_i2.RecycledTask>>);
}

/// A class which mocks [PointsProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockPointsProvider extends _i1.Mock implements _i6.PointsProvider {
  MockPointsProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.UserPoints get userPoints =>
      (super.noSuchMethod(
            Invocation.getter(#userPoints),
            returnValue: _FakeUserPoints_1(
              this,
              Invocation.getter(#userPoints),
            ),
          )
          as _i3.UserPoints);

  @override
  int get currentPoints =>
      (super.noSuchMethod(Invocation.getter(#currentPoints), returnValue: 0)
          as int);

  @override
  List<_i3.PointsRecord> get records =>
      (super.noSuchMethod(
            Invocation.getter(#records),
            returnValue: <_i3.PointsRecord>[],
          )
          as List<_i3.PointsRecord>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> addPoints(int? points) =>
      (super.noSuchMethod(
            Invocation.method(#addPoints, [points]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deductPoints(int? points) =>
      (super.noSuchMethod(
            Invocation.method(#deductPoints, [points]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updatePoints(int? points) =>
      (super.noSuchMethod(
            Invocation.method(#updatePoints, [points]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> addPointsWithRecord({
    required int? points,
    required String? type,
    required String? description,
    int? relatedId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addPointsWithRecord, [], {
              #points: points,
              #type: type,
              #description: description,
              #relatedId: relatedId,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deductPointsWithRecord({
    required int? points,
    required String? type,
    required String? description,
    int? relatedId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deductPointsWithRecord, [], {
              #points: points,
              #type: type,
              #description: description,
              #relatedId: relatedId,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> hasRecordForTypeAndRelatedId(String? type, int? relatedId) =>
      (super.noSuchMethod(
            Invocation.method(#hasRecordForTypeAndRelatedId, [type, relatedId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> refreshRecords() =>
      (super.noSuchMethod(
            Invocation.method(#refreshRecords, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
