import 'scratch_model.dart';

/// 各档位（10 / 20 / 50 积分）的默认奖池数据。
///
/// 从 scratch_provider.dart 抽出（规范 6：单文件 ≤500 行）。这块数据量大且与业务
/// 逻辑无关，单独成文件更便于查阅与维护。
final Map<int, List<PrizeItem>> defaultPrizePoolsByCost = {
    10: [
      PrizeItem(
        id: 'default_10_5',
        name: '5积分',
        type: 'integral',
        value: 5,
        weight: 1.0,
        isDefault: true,
      ),
      PrizeItem(
        id: 'default_10_8',
        name: '8积分',
        type: 'integral',
        value: 8,
        weight: 1.0,
        isDefault: true,
      ),
      PrizeItem(
        id: 'default_10_10',
        name: '10积分',
        type: 'integral',
        value: 10,
        weight: 1.0,
        isDefault: true,
      ),
      PrizeItem(
        id: 'default_10_12',
        name: '12积分',
        type: 'integral',
        value: 12,
        weight: 1.0,
        isDefault: true,
      ),
      PrizeItem(
        id: 'default_10_15',
        name: '15积分',
        type: 'integral',
        value: 15,
        weight: 1.0,
        isDefault: true,
      ),
      PrizeItem(
        id: 'default_10_20',
        name: '20积分',
        type: 'integral',
        value: 20,
        weight: 1.0,
        isDefault: true,
      ),
      PrizeItem(
        id: 'default_10_30',
        name: '30积分',
        type: 'integral',
        value: 30,
        weight: 1.0,
        isDefault: true,
      ),
      PrizeItem(
        id: 'default_10_50',
        name: '50积分',
        type: 'integral',
        value: 50,
        weight: 1.0,
        isDefault: true,
      ),
      PrizeItem(
        id: 'default_10_80',
        name: '80积分',
        type: 'integral',
        value: 80,
        weight: 1.0,
        isDefault: true,
      ),
      PrizeItem(
        id: 'default_10_100',
        name: '100积分',
        type: 'integral',
        value: 100,
        weight: 1.0,
        isDefault: true,
      ),
    ],
    20: [
      PrizeItem(
        id: 'default_20_10',
        name: '10积分',
        type: 'integral',
        value: 10,
        weight: 1.0,
        isDefault: true,
      ),
      PrizeItem(
        id: 'default_20_15',
        name: '15积分',
        type: 'integral',
        value: 15,
        weight: 1.0,
        isDefault: true,
      ),
      PrizeItem(
        id: 'default_20_20',
        name: '20积分',
        type: 'integral',
        value: 20,
        weight: 1.0,
        isDefault: true,
      ),
      PrizeItem(
        id: 'default_20_25',
        name: '25积分',
        type: 'integral',
        value: 25,
        weight: 1.0,
        isDefault: true,
      ),
      PrizeItem(
        id: 'default_20_30',
        name: '30积分',
        type: 'integral',
        value: 30,
        weight: 1.0,
        isDefault: true,
      ),
      PrizeItem(
        id: 'default_20_50',
        name: '50积分',
        type: 'integral',
        value: 50,
        weight: 1.0,
        isDefault: true,
      ),
      PrizeItem(
        id: 'default_20_80',
        name: '80积分',
        type: 'integral',
        value: 80,
        weight: 1.0,
        isDefault: true,
      ),
      PrizeItem(
        id: 'default_20_100',
        name: '100积分',
        type: 'integral',
        value: 100,
        weight: 1.0,
        isDefault: true,
      ),
      PrizeItem(
        id: 'default_20_150',
        name: '150积分',
        type: 'integral',
        value: 150,
        weight: 1.0,
        isDefault: true,
      ),
      PrizeItem(
        id: 'default_20_200',
        name: '200积分',
        type: 'integral',
        value: 200,
        weight: 1.0,
        isDefault: true,
      ),
    ],
    50: [
      PrizeItem(
        id: 'default_50_20',
        name: '20积分',
        type: 'integral',
        value: 20,
        weight: 1.0,
        isDefault: true,
      ),
      PrizeItem(
        id: 'default_50_30',
        name: '30积分',
        type: 'integral',
        value: 30,
        weight: 1.0,
        isDefault: true,
      ),
      PrizeItem(
        id: 'default_50_40',
        name: '40积分',
        type: 'integral',
        value: 40,
        weight: 1.0,
        isDefault: true,
      ),
      PrizeItem(
        id: 'default_50_50',
        name: '50积分',
        type: 'integral',
        value: 50,
        weight: 1.0,
        isDefault: true,
      ),
      PrizeItem(
        id: 'default_50_80',
        name: '80积分',
        type: 'integral',
        value: 80,
        weight: 1.0,
        isDefault: true,
      ),
      PrizeItem(
        id: 'default_50_100',
        name: '100积分',
        type: 'integral',
        value: 100,
        weight: 1.0,
        isDefault: true,
      ),
      PrizeItem(
        id: 'default_50_150',
        name: '150积分',
        type: 'integral',
        value: 150,
        weight: 1.0,
        isDefault: true,
      ),
      PrizeItem(
        id: 'default_50_200',
        name: '200积分',
        type: 'integral',
        value: 200,
        weight: 1.0,
        isDefault: true,
      ),
      PrizeItem(
        id: 'default_50_300',
        name: '300积分',
        type: 'integral',
        value: 300,
        weight: 1.0,
        isDefault: true,
      ),
      PrizeItem(
        id: 'default_50_500',
        name: '500积分',
        type: 'integral',
        value: 500,
        weight: 1.0,
        isDefault: true,
      ),
    ],
};
